## YAML Template.
services:

  backend:
    container_name: todoList # Nombre del contenedor
    build: ./backend # Ubicación del archivo Dockerfile
    ports: 
      - 8080:8080
    networks: 
      - appTodoList
    volumes:
      - ./backend:/app # Ubicación donde se guardarán los datosw
    environment: # Se reemplaza la ruta de la base de datos. En vez de "localhost" se dirige al contenedor "m5-mysql"
      SPRING_DATASOURCE_URL: jdbc:mysql://m5-mysql:3306/softtek
    depends_on: # "backend" inicia despues que se termine de cargar el servicio "db"
      db:
        condition: service_healthy

  # Servicio 'db', contiene las configuraciones para la base de datos
  baseDeDatos:
    container_name: m5-mysql # Nombre del contenedor
    image: mysql:8.0.33 # Imagen de la base de datos, en este caso se usa MySQL
    ports: # Puertos que se exponen
      - 3306:3306
    environment: # Variables de entorno
      MYSQL_DATABASE: softtek
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 

    volumes:  # Ubicación donde se guardarán los datos
      - academia_db:/var/lib/mysql
    networks:  # Red de Docker por la que se comunicará con otros contenedores
      - appTodoList
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20

networks: # Configuración de la red de docker
  appTodoList:
    driver: bridge
volumes: # Configuración del almacen de datos de docker
  academia_db: